### ISSUE TITLE
Missing stderr/stdout on pulsar jobs

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/pulsar#211]
Not sure if this is a duplicate of https://github.com/galaxyproject/pulsar/issues/158 but I recently ran some circos jobs on EU (which go through pulsar). All of the jobs errored out. https://usegalaxy.eu/u/helena-rasche/h/circos-multi-plot

- "Remote job server indicated a problem running or monitoring this job."
- No stderr
- No stdout

I had to contact the admins to help debug this issue and they could look at the job logs directly. It would be super useful for me if the job stderr/out were present, since any errors during training which uses EU will only have this cryptic message.

Thanks for the tool debugging help @gmauro @bgruening

**Comment by hexylena** [comment]
This bit me again and it's still troublesome. Super simple error in my circos config but required a fair bit of work to track down the stderr.

**Comment by hexylena** [comment]
This is biting us during the Smörgåsbord, we could help the student if only we could see the job logs. Instead we need to wait for an EU admin to login to the specific pulsar cluster, and track down the exact error message from that job ID.

**Comment by natefoo** [comment]
We did fix this at one point: galaxyproject/galaxy#5535

Not sure what happened in the meantime or if this is a new problem. Galaxy has since started separating tool and job stdout/stderr and making Pulsar do the same is a top priority IMO.

**Comment by gmauro** [comment]
About the Smörgåsbord issue, the job completed properly in the remote cluster but, Pulsar failed to transfer the first output  and then the job failed
```
Feb 17 11:27:49 pulsar-central-manager.xchem.novalocal pulsar[76650]: 2021-02-17 11:27:49,766 INFO  [pulsar.managers.util.retry][[manager=production]-[action=postprocess]-[job=15079744]] Failed to execute staging out file /data/share/staging/15079744/working/output.txt via FileAction[path=None,action_type=remote_transfer,url=https://usegalaxy.eu/_job_files?job_id=11ac94870d0bb33a3414d3c5ba2732db&job_key=b269333ccac1e9149df5017c17bcfa0c&path=None&file_type=output_workdir], retrying in 292.0 seconds.
Feb 17 11:32:42 pulsar-central-manager.xchem.novalocal pulsar[76650]: 2021-02-17 11:32:42,030 ERROR [pulsar.managers.stateful][[manager=production]-[action=postprocess]-[job=15079744]] Failed to postprocess results for job id 15079744

```

**Comment by hexylena** [comment]
Relatedly, some of my circos jobs show:

```
Remote job server indicated a problem running or monitoring this job.
```

while the stderr/out contains the proper error message that would've been reported if running locally, if it wasn't for the pulsar error message. fun!

**Comment by natefoo** [comment]
Yeah I think this may be more of a Pulsar runner issue, although there may still be cases where it's failing to transfer the stdout/stderr (@gmauro do you know if in that specific case the tool produced any stdout or stderr on the Pulsar side?)

For example, in a recent SPAdes failure I got the full stdout in the bug report (from job.tool_stdout in the db). The Pulsar runner (in Galaxy) is I believe what sets job.info = "Remote job server indicated a problem running or monitoring this job." and it does this any time Pulsar reports a failure to do its part of finishing a job, which it will report that any time it fails to collect a defined output because the tool failed and didn't produce that output. In this case the runner should probably do whatever the other runners do. I think there is an issue that discusses this somewhere that I would link, but I can't find it.

**Comment by gmauro** [comment]
> Yeah I think this may be more of a Pulsar runner issue, although there may still be cases where it's failing to transfer the stdout/stderr (@gmauro do you know if in that specific case the tool produced any stdout or stderr on the Pulsar side?)

stdout and stderr were present and empty.
